version: '3'
services:
  kafka:
    image: landoop/fast-data-dev:latest
    ports:
      - "3030:3030"
      - "9092:9092"
      - "2181:2181"
      - "8081:8081"
    environment:
      - ADV_HOST=127.0.0.1